### ISSUE TITLE
Broken image links on readthedocs

### ISSUE THREAD

**Issue by eeintech** [inventree/inventree-docs#2]
Looks like image links might be broken on readthedocs, they don't show.... For instance:
https://inventree.readthedocs.io/en/latest/stock/adjust/

The link look correct: `/assets/images/stock/stock_move.png` for the first picture.

Need investigation!

**Comment by SchrodingersGat** [comment]
The issue here is that when hosting locally, the asset files are at (for example):

`http://127.0.0.1/assets/images/part/hello.png`

But when hosted online:

`https://inventree.readthedocs.io/en/latest/assets/images/part/hello.png`

It is the extra */en/latest/* which is mucking it up here.

The interim solution is that I have now hard-coded in the extra */en/latest/* path. However this means it will no longer render images properly when running on local server.

The solution will be for the template file to determine if it is compiling locally or on readthedocs.

This *should* be possible:

- https://docs.readthedocs.io/en/stable/faq.html#how-do-i-change-behavior-when-building-with-read-the-docs
- https://mkdocs.readthedocs.io/en/restructure-compat/user-guide/custom-themes/#base_url
- https://docs.readthedocs.io/en/stable/development/design/theme-context.html

However none of the options I have tried have worked yet.

**Comment by eeintech** [comment]
@SchrodingersGat Very strange! Looking at the commit history, I would have thought that either `{{ base_url }}` or `READTHEDOCS` environment variable would have worked. I searched a bit on my side on did not find a better option to handle build dependencies...

**Comment by eeintech** [comment]
I just found out the macros plugin can also retrieve context:
https://mkdocs-macros-plugin.readthedocs.io/en/latest/pages/#batteries-included-defaut-variables

From what I could see the `config.site_url` seems most likely candidate, but not certain...

**Comment by eeintech** [comment]
Solved by PR #8
