### ISSUE TITLE
[RFQ] Move docs into main repo

### ISSUE THREAD

**Issue by matmair** [inventree/inventree-docs#375]
RFQ:
Moving the docs into the main repo would enable us to make the release easier and add autogenerated docs from the docstrings.

**Comment by matmair** [comment]
@SchrodingersGat thoughts?

**Comment by SchrodingersGat** [comment]
The release would certainly be easier, and I am on board with auto-generated docstrings from code.

Maybe we move these docs once we also migrate to the new website?

**Comment by eeintech** [comment]
The way I see it (and I may be wrong), the auto-generated docstring creates a documentation for developers and code contributors.
However, this _light_ (in the sense that there is almost no need for external dependencies and few files) repo contains documentation for InvenTree users, including developers.

I would be in favor to keep this repo separate because contributions are much simpler to post and review than on the main code repo.

But maybe I am missing part of the equation.

**Comment by SchrodingersGat** [comment]
@eeintech as a documentation contributor, you don't need to install all the source dependencies, just the mkdocs ones.

**Comment by matmair** [comment]
@eeintech the idea is to:
a) remove the disconnect between code and doc releases
b) make it easier for plugin starters to discover classes etc. you can not expect ppl. to dig through the whole codebase to find out how it works.

**Comment by eeintech** [comment]
> @eeintech as a documentation contributor, you don't need to install all the source dependencies, just the mkdocs ones.

Alright, as long as it doesn't add any burden on potential doc contributors which is my main concern.

> @eeintech the idea is to: a) remove the disconnect between code and doc releases b) make it easier for plugin starters to discover classes etc. you can not expect ppl. to dig through the whole codebase to find out how it works. c) move more to a mono-repo so that issues etc are in the same dir

All those points make sense, as I said I was only concerned about putting the bar higher for doc contributors. I'm sure it's for the best :smile:
